import { IWork } from './mocks.types';

export const WORKS: IWork[] = [
  {
    id: 1,
    title: 'Угловые кухни на параллельных стенах',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница и фартук Кедр (мрамор беж)',
    ],
    image: [
      '/images/kitchens/1/1.webp',
      '/images/kitchens/1/2.webp',
      '/images/kitchens/1/3.webp',
      '/images/kitchens/1/4.webp',
      '/images/kitchens/1/5.webp',
      '/images/kitchens/1/6.webp',
      '/images/kitchens/1/7.webp',
      '/images/kitchens/1/8.webp',
      '/images/kitchens/1/9.webp',
      '/images/kitchens/1/10.webp',
      '/images/kitchens/1/11.webp',
    ],
  },
  {
    id: 2,
    title: 'Белая кухня в эмали',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница и фартук : АМК Троя (паладина светлая)',
      'Фурнитура * Firmax',
    ],
    image: [
      '/images/kitchens/2/1.webp',
      '/images/kitchens/2/2.webp',
      '/images/kitchens/2/3.webp',
      '/images/kitchens/2/4.webp',
      '/images/kitchens/2/5.webp',
      '/images/kitchens/2/6.webp',
    ],
  },
  {
    id: 3,
    title: 'Кухня в скандинавском стиле',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница * АМК Троя (дуб вотан)',
    ],
    image: [
      '/images/kitchens/3/1.webp',
      '/images/kitchens/3/2.webp',
      '/images/kitchens/3/3.webp',
      '/images/kitchens/3/4.webp',
      '/images/kitchens/3/5.webp',
      '/images/kitchens/3/6.webp',
      '/images/kitchens/3/7.webp',
    ],
  },
  {
    id: 4,
    title: 'Кухня в стиле лофт',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница Кедр (дуб вотан)',
      'Фурнитура * Blum',
    ],
    image: [
      '/images/kitchens/4/1.webp',
      '/images/kitchens/4/2.webp',
      '/images/kitchens/4/3.webp',
      '/images/kitchens/4/4.webp',
      '/images/kitchens/4/5.webp',
      '/images/kitchens/4/6.webp',
      '/images/kitchens/4/7.webp',
      '/images/kitchens/4/8.webp',
      '/images/kitchens/4/9.webp',
    ],
  },
  {
    id: 5,
    title: 'Кухня у окна',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница * АМК Троя (черный гранит)',
    ],
    image: [
      '/images/kitchens/5/1.webp',
      '/images/kitchens/5/2.webp',
      '/images/kitchens/5/3.webp',
    ],
  },
  {
    id: 6,
    title: 'Угловая кухня в белом цвете',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница * Скиф (Травертин)',
      'Фурнитура * Blum',
    ],
    image: [
      '/images/kitchens/6/1.webp',
      '/images/kitchens/6/2.webp',
      '/images/kitchens/6/3.webp',
      '/images/kitchens/6/4.webp',
      '/images/kitchens/6/5.webp',
      '/images/kitchens/6/6.webp',
      '/images/kitchens/6/7.webp',
      '/images/kitchens/6/8.webp',
      '/images/kitchens/6/9.webp',
      '/images/kitchens/6/10.webp',
    ],
  },
  {
    id: 7,
    title: 'Угловая кухня с окном',
    category: 'Кухни',
    description: [
      'Фасады МДФ в пленке ПВХ',
      'Корпус ЛДСП Lamarty ',
      'Столешница * АМК Троя (дуб вотан)',
    ],
    image: [
      '/images/kitchens/7/1.webp',
      '/images/kitchens/7/2.webp',
      '/images/kitchens/7/3.webp',
      '/images/kitchens/7/4.webp',
    ],
  },
  {
    id: 8,
    title: 'Шкаф в прихожей',
    category: 'Шкафы',
    description: [
      'Шкаф является стеной и проем в кухню.',
      'Фасады * МДФ в пленке ПВХ',
      'Корпус * ЛДСП Lamarty',
    ],
    image: [
      '/images/wardrobes/1/1.webp',
      '/images/wardrobes/1/2.webp',
      '/images/wardrobes/1/3.webp',
      '/images/wardrobes/1/4.webp',
      '/images/wardrobes/1/5.webp',
    ],
  },
  {
    id: 9,
    title: 'Шкаф в спальной комнате',
    category: 'Шкафы',
    description: ['Фасады * МДФ в пленке ПВХ', 'Корпус * ЛДСП Lamarty'],
    image: [
      '/images/wardrobes/2/2.webp',
      '/images/wardrobes/2/2.webp',
      '/images/wardrobes/2/3.webp',
      '/images/wardrobes/2/4.webp',
    ],
  },
  {
    id: 10,
    title: 'Шкаф в спальной комнате',
    category: 'Шкафы',
    description: ['Фасады * МДФ в пленке ПВХ', 'Корпус * ЛДСП Lamarty'],
    image: [
      '/images/wardrobes/3/1.webp',
      '/images/wardrobes/3/2.webp',
      '/images/wardrobes/3/3.webp',
      '/images/wardrobes/3/4.webp',
      '/images/wardrobes/3/5.webp',
    ],
  },
  {
    id: 11,
    title: 'Шкаф-купе с зеркалом',
    category: 'Шкафы-купе',
    description: ['Корпус лдсп Egger', 'Направляющие Premial'],
    image: [
      '/images/slidingWardrobes/1/1.webp',
      '/images/slidingWardrobes/1/2.webp',
      '/images/slidingWardrobes/1/3.webp',
      '/images/slidingWardrobes/1/4.webp',
      '/images/slidingWardrobes/1/5.webp',
    ],
  },
  {
    id: 12,
    title: 'Шкаф-купе с зеркальными дверьми',
    category: 'Шкафы-купе',
    description: ['Корпус * ЛДСП Lamarty', 'Направляющие * Aristo '],
    image: [
      '/images/slidingWardrobes/2/1.webp',
      '/images/slidingWardrobes/2/2.webp',
      '/images/slidingWardrobes/2/3.webp',
      '/images/slidingWardrobes/2/4.webp',
    ],
  },
  {
    id: 13,
    title: 'Шкаф-купе с золотым профилем',
    category: 'Шкафы-купе',
    description: ['Корпус лдсп Egger', 'Направляющие Premial'],
    image: [
      '/images/slidingWardrobes/3/1.webp',
      '/images/slidingWardrobes/3/2.webp',
      '/images/slidingWardrobes/3/3.webp',
      '/images/slidingWardrobes/3/4.webp',
      '/images/slidingWardrobes/3/5.webp',
    ],
  },
  {
    id: 14,
    title: 'Шкаф-купе с открытыми полками',
    category: 'Шкафы-купе',
    description: ['Корпус лдсп Egger', 'Направляющие Premial'],
    image: [
      '/images/slidingWardrobes/4/1.webp',
      '/images/slidingWardrobes/4/2.webp',
      '/images/slidingWardrobes/4/3.webp',
      '/images/slidingWardrobes/4/4.webp',
    ],
  },
  {
    id: 15,
    title: 'Гардеробная в 3 стены',
    category: 'Гардеробные',
    description: ['нет информации'],
    image: [
      '/images/dressingRooms/1/1.webp',
      '/images/dressingRooms/1/2.webp',
      '/images/dressingRooms/1/3.webp',
      '/images/dressingRooms/1/4.webp',
      '/images/dressingRooms/1/5.webp',
      '/images/dressingRooms/1/6.webp',
      '/images/dressingRooms/1/7.webp',
    ],
  },
  {
    id: 16,
    title: 'Телевизионная зона',
    category: 'Комоды',
    description: ['Фасады лдсп egger', 'Корпус лдсп egger', 'Панель мдф в пленке пвх'],
    image: [
      '/images/dressers/1/1.webp',
      '/images/dressers/1/2.webp',
      '/images/dressers/1/3.webp',
      '/images/dressers/1/4.webp',
      '/images/dressers/1/5.webp',
    ],
  },
];
